import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  opsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [{type: 'autogenerated', dirName: '00_overview'}],
    },
    {
      type: 'category',
      label: 'Weekly Board',
      items: [{type: 'autogenerated', dirName: '01_weekly_board'}],
    },
    {
      type: 'category',
      label: 'Governance Map',
      items: [{type: 'autogenerated', dirName: '02_governance_map'}],
    },
    {
      type: 'category',
      label: 'Route Cards',
      items: [{type: 'autogenerated', dirName: '03_route_cards'}],
    },
    {
      type: 'category',
      label: 'Digital Support Index',
      items: [{type: 'autogenerated', dirName: '04_digital_support_index'}],
    },
    {
      type: 'category',
      label: 'Full Context',
      items: [{type: 'autogenerated', dirName: '05_full_context'}],
    },
    {
      type: 'category',
      label: 'Printables',
      items: [{type: 'autogenerated', dirName: '06_printables'}],
    },
    {
      type: 'category',
      label: 'Backlog',
      items: [{type: 'autogenerated', dirName: '09_backlog'}],
    },
    {
      type: 'category',
      label: 'Archive',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '10_archive'}],
    },
  ],
};

export default sidebars;
